# Pytorch Tensors Explanined - Neural Network Programming

In [1]:
import torch
import numpy as np

# Tensor Class
Tensors in PyTorch are represented using "torch.Tensor" class

In [2]:
t= torch.Tensor()
type(t)

torch.Tensor

# Tensor Attributes


In [3]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [4]:
device= torch.device('cuda:0')
device

device(type='cuda', index=0)

# Types of Tensor Operations;

### -Reshaping
### -Element-wise
### -Reduction
### -Access

# Reshaping


In [5]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [7]:
t.shape

torch.Size([3, 4])

In [9]:
t.numel() # Product of dimenssions = Total number of elements in tensor

12

In [11]:
len(t.shape) # number of dimenssions of tensor = rank

2

In [12]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [13]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [14]:
t


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [15]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

# Squeezing 

### Squeezing provides a flattened tensor
#### FLATTENED TENSOR == Tensor with reduced rank (reduced dimension)

In [22]:
def flatten(tensor):         # For flattening the tensor
    tensor= tensor.reshape(1, -1)
    tensor= tensor.squeeze()
    return tensor

In [23]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

# CNN Flatten Operation Visualization - Tensor Batch Preprocessing for DL 

In [24]:
t1 = torch.tensor([                 # Image 1
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([                  # Image 2
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([                  # Image 1
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [36]:
t_n =torch.stack((t1, t2, t3)) # "stack" to combine all the three tensors
t_n.shape

torch.Size([3, 4, 4])

In [37]:
# 3- Batch size
# 4,4- Height, Width
t_n


tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [42]:
t_n= t_n.reshape(3,1,4,4) # Adding '1' for the colour channel, as this wont even affect the t.numel() 
t_n

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

##### Indexing 

In [46]:
t_n[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [47]:
t_n[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [48]:
t_n[0][0][0]

tensor([1, 1, 1, 1])

In [49]:
t_n[0][0][0][0]

tensor(1)

### Flattening for CNN 

In [50]:
t_n.flatten(start_dim=1) # Flattening each image 
# Flattened Image 1=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
# Flattened Image 2=[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [52]:
t_n.flatten(start_dim=1).shape

torch.Size([3, 16])

# Broadcasting And Element-Wise Operations With PyTorch

    Element-wise operations are extremely common operations with tensors in neural network programming. Let’s lead this discussion off with a definition of an element-wise operation.

    An element-wise operation is an operation between two tensors that operates on corresponding elements within the respective tensors.

### For Element-wise Operation, both tensors should have same shape (not including Broadcasting)

In [53]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)



t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [55]:
t1+t2 # All arithmetic operations(+, -, *, /) are element-wise operations

tensor([[10., 10.],
        [10., 10.]])

### Broadcasting; t1 + scalar 

In [57]:
t1+ 2 # Scaler, 

tensor([[3., 4.],
        [5., 6.]])

In [59]:
t3= torch.tensor([
    [2,4]
], dtype= torch.float32)

In [66]:
t3= np.broadcast_to(t3.numpy(), t1.shape)
t3

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [67]:
t1 + t3

tensor([[3., 6.],
        [5., 8.]])

### Element-wise == Component-wise == Point-wise 

# Tensor Reduction Operations and Argmax

A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor.

In [68]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [70]:
t.sum() # Reduction operation

tensor(8.)

In [71]:
t.prod() # Reduction operation

tensor(0.)

In [72]:
t.mean() # Reduction operation

tensor(0.8889)

In [73]:
t.std() # Reduction operation

tensor(1.1667)

In [74]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [75]:
t.sum(dim=0) #across axis 1

tensor([6., 6., 6., 6.])

In [76]:
t.sum(dim=1) #across axis 2

tensor([ 4.,  8., 12.])

In [79]:
t.max()

tensor(3.)

In [80]:
t.argmax() # returns index of max value of flattened tensor t 

tensor(11)

In [83]:
t.mean() # Output is tensor

tensor(2.)

In [84]:
t.mean().item() # Output is the actual value

2.0

In [86]:
t.mean(dim=0).tolist()

[2.0, 2.0, 2.0, 2.0]